import {useEffect, useState} from "react";

import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [currentMessage, setCurrentMessage] = useState("");
  const [messages, setMessages] = useState([]);
  const [newMessage, setNewMessage] = useState("");

  useEffect(()=>{
    if (newMessage.length > 0){
      setMessages([...messages, newMessage]);
      setNewMessage("");
    }
  }, [newMessage])



  useEffect(()=>{
    let subscribed = true;
    
   
    const subscribe = async()=>{

      const response = await fetch("/api/message");

      if (response.status === 502){
        // connection timeout

      }else if (response.status !== 200){

        alert(response.statusText);
      } else{
        const data = await response.json();

        setNewMessage(data.message)
      }


      if (subscribed){
         subscribe();
      }
      
    }

    subscribe();
    return ()=>{subscribed = false; console.log("stopping")}
  }, []);


const sendMessage= async()=>{
  console.log("sending");
  const response = await fetch("/api/message", 
    {method:"POST",
    headers: new Headers({ "Content-type": "application/json" }),
    body: JSON.stringify({message: currentMessage})});

  if (! response.ok){
    alert(response.statusText);
  }else{
    setCurrentMessage("");
  }

};




const messageItems = messages.map((msg)=> <li key={msg}>{msg}</li>)



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Polling example
        </h1>
<ul>
  {messageItems}
</ul>

<input type="text"
value={currentMessage}
onChange={(event)=>{setCurrentMessage(event.target.value)}}
onKeyPress={(event)=>{if (event && event.key === "Enter"){
  sendMessage();
}}}
/>

<input type="button"
value="Send"
onClick={sendMessage}
/>

        </main>
      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
